### ISSUE TITLE
Configure UI Fixes

### ISSUE THREAD

**Issue by mbrown1413** [ITNG/yurika#22]
Crawler:
  * You can click "Save Crawler" before any links are added. Gray out "Save Crawler" until links are added.
  * You can add links then accidentally click "Save Crawler" and loose the entered links. Not sure the best way to fix this, but one possibility is to make "Save Crawler" also add any links present.

MindMap:
  * Clicking "Save MindMap" without uploading anything causes that section to be marked completed. Gray out "Save MindMap" until something is uploaded.

Dictionaries:
  * Make it clear that you either load system dictionaries, or create your own, not both.

Query:
  * "Needs intuitive way of explaining/showing how this form works"
  * Selecting "Regular Expressions" and a dictionary searches for the name of that dictionary?
   * Make the printout of the current query human readable (not "part_of_speech.CD AND regex.5")

**Comment by mbrown1413** [comment]
To make things clearer in the "Query" section I was thinking of changing "Regular Expression" in the dropdown menu to something like "MindMap Term" or "MindMap Node" or "MindMap Expression". I want to keep the language consistent though. Any thoughts on this?

**Comment by mejohn** [comment]
I like MindMap Term, since it uses the node name if regex isn't available

**Comment by mbrown1413** [comment]
Agreed. Descriptions added with c583ad9d1912fed92c2899825bfbab11db76e442.

Left to do:

  * Combine forms for Crawler so you can't hit the wrong submit button and loose added urls.
  * Same thing but for Dictionaries.
  * Don't show "Load System Dictionaries" link if there's nothing to load. (is this necessary?)

Changing the query print-out to be human readable I'm considering to be part of #29.

**Comment by mbrown1413** [comment]
Fixed with #56. Thanks @rpkilby!
